### PR TITLE
woocommerce_moldovaagroindbank_order_description filter added for order description customisation

### PR DESCRIPTION
**Pull request by todoshcenko**
Plugin has only 2 predefined variables for order description:
 * `%1$s` - order identifier
 * `%2$s` - order positions

But sometimes other order data is required (as example if order number is required instead of identifier).

This solution keeps full backward compatibility and adds possibility to make own description.

### CODE REVIEW

**Comment by todoshcenko** [comment]
@alexminza Can you check, please?

**Comment by alexminza** [comment]
> @alexminza Can you check, please?

@todoshcenko I have left some comments/questions in your PR - please have a look and address/answer them. Thanks!

**Comment by todoshcenko** [comment]
> @todoshcenko I have left some comments/questions in your PR - please have a look and address/answer them. Thanks!

Sorry but i can't find any comments/reviews :( 
Did you submit review? May be i did something wrong?

**Comment by alexminza** [comment]
> > @todoshcenko I have left some comments/questions in your PR - please have a look and address/answer them. Thanks!
> 
> Sorry but i can't find any comments/reviews :( Did you submit review? May be i did something wrong?

You can find the comments here https://github.com/alexminza/wc-moldovaagroindbank/pull/23/files inline with the corresponding code block.

Please revert the changes to `save_temp_file` and commit.

**Comment by alexminza** [comment]
> > @todoshcenko I have left some comments/questions in your PR - please have a look and address/answer them. Thanks!
> 
> Sorry but i can't find any comments/reviews :( Did you submit review? May be i did something wrong?

See also https://github.com/alexminza/wc-moldovaagroindbank/pull/23/files

Screenshot 2022-11-29 at 12 06 26

**Comment by todoshcenko** [comment]
@alexminza problem is that i don't see anything ((

Screenshot 2022-11-29 at 10 48 03

**Review by alexminza — APPROVED** [review]
LGTM

**Pull request merged**
